apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: kube-agent
  name: kube-agent
  namespace: wodby
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kube-agent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: kube-agent
    spec:
      containers:
      - name: kube-agent
        image: wodby/kube-agent:dev
        imagePullPolicy: IfNotPresent
        env:
        - name: KUBE_AGENT_NODE_TOKEN
          value: random-token
        - name: KUBE_AGENT_NAME
          value: kube_agent_7ed990cc-fafe-4741-85a1-55d3ba03d8d4
        - name: KUBE_AGENT_SERVER_HOST
          value: host.docker.internal
        - name: KUBE_AGENT_SERVER_PORT
          value: "443"
        - name: KUBE_AGENT_QUEUE
          value: kube_agent_7ed990cc-fafe-4741-85a1-55d3ba03d8d4_q
        - name: KUBE_AGENT_EXCHANGE
          value: kube_agent.dx
        - name: KUBE_AGENT_SKIP_VERIFY
          value: "1"
#      - name: redis
#        image: wodby/redis:5
#        imagePullPolicy: IfNotPresent
