version: "3"

services:
  nginx:
    container_name: "kube_agent_nginx"
    image: nginx
    depends_on:
      - rabbitmq
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./key.pem:/etc/ssl/certs/key.pem
      - ./certificate.pem:/etc/ssl/certs/certificate.pem
    ports:
      - "443:443"

  rabbitmq:
    container_name: "kube_agent_rabbitmq"
    image: rabbitmq:3.7-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test
      RABBITMQ_NODENAME: rabbit@localhost

#  api:
#    container_name: "wodby_hub_api"
#    image: wodby/php:7.1-dev
#    command: "php -S 0.0.0.0:9000 -t /var/www/html"
#    volumes:
#    - ./index.php:/var/www/html/index.php
